### PR TITLE
Fix NarayanaLRAClient coordinator URL priority first by constructor then by property

### LINKED ISSUE #175: Lra client is started based on config instead of parameter value
NarayanaLRAClient client = new NarayanaLRAClient("http://localhost:49101/lra-coordinator/lra-coordinator");

When i am testing failure of the client, I discovered that if the coordinator pasted there isnt available, it will eventually start the one from lra.coodinator.urls. 

 private void clusterConfig(URI coordinatorUrl) {
        if (CONFIG.getOptionalValue(COORDINATOR_URLS_KEY, String.class).isEmpty()) {
            this.coordinatorUrl = coordinatorUrl;
            this.coordinatorCount = 1;
        } else {
            String coordinators = getConfigProperty(COORDINATOR_URLS_KEY, coordinatorUrl.toASCIIString());

            this.coordinatorUrl = toURI(coordinators.split(",")[0]);
            this.coordinatorCount = coordinators.chars().filter(ch -> ch == ',').count() + 1;

### PR DESCRIPTION
**Pull request by xstefank**
Note that this is my take into how it should look like but I am willing to adjust it if agreed differently. This PR proposes:

- First look into whatever user passes as constructor argument
- If nothing, then look into "lra.coordinator.url" property 

See that I dropped "lra.coordinator.urls" (note the s at the end) because this is the same config also in the original code and there is no point in having two keys for the same thing as it might confuse users. I believe this is the best solution but feel free to suggest otherwise.

Fixes #175

### CODE REVIEW

File: client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java [hunk 1]
```diff
@@ -181,6 +177,7 @@ public NarayanaLRAClient() {
      * @param port port where the LRA coordinator will be contacted
      * @param coordinatorPath path where the LRA coordinator will be contacted
      */
+    @Deprecated(since = "1.0.3.Final", forRemoval = true)
```
Comment (marcosgopen) [inline client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java]: Not sure about this, see issue https://issues.redhat.com/browse/JBTM-3940
"Now that the [client api](https://github.com/jbosstm/narayana/blob/7.1.0.Final/rts/lra/client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java#L93) has been moved to an internal package the @Deprecated annotation can be removed."

**Comment by mmusgrov** [comment]
We now need to follow up with the LRA ascidocs to reflect this change.

File: client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java (hunk 1 above)
Comment (tomjenkinson) [reply client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java]: It's in the internal package so we don't actually need to deprecate it IMO. But we can notify developers on Zulip of the change if we want?

Comment (mmusgrov) [reply client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java]: > unless we can move to JPMS :)

Yes that is the plan.
